IF (QUICKERFIX_INCLUDE_DIR AND QUICKERFIX_LIBRARIES)
    SET (Quickerfix_FOUND TRUE)
ELSE(QUICKERFIX_INCLUDE_DIR AND QUICKERFIX_LIBRARIES)
    FIND_PATH(QUICKERFIX_INCLUDE_DIR quickfix/Session.h
		/usr/include/
		/usr/local/include/
	)

    MESSAGE(STATUS "Include path: ${QUICKERFIX_INCLUDE_DIR}")
	
	FIND_LIBRARY(QUICKERFIX_LIBRARIES NAMES quickfix 
		PATHS
        /usr/lib
        /usr/local/lib
	)

    MESSAGE(STATUS "Library: ${QUICKERFIX_LIBRARIES}")

    IF(QUICKERFIX_INCLUDE_DIR AND QUICKERFIX_LIBRARIES)
        SET(Quickerfix_FOUND TRUE)
        MESSAGE(STATUS "Found quickfix: ${QUICKERFIX_INCLUDE_DIR}, ${QUICKERFIX_LIBRARIES}")
        INCLUDE_DIRECTORIES(${QUICKERFIX_INCLUDE_DIR})
    ELSE(QUICKERFIX_INCLUDE_DIR AND QUICKERFIX_LIBRARIES)
        SET(Quickerfix_FOUND FALSE)
		MESSAGE(STATUS "quickerfix library not found.")
    ENDIF(QUICKERFIX_INCLUDE_DIR AND QUICKERFIX_LIBRARIES)
  
    MARK_AS_ADVANCED(QUICKERFIX_INCLUDE_DIR QUICKERFIX_LIBRARIES)
ENDIF(QUICKERFIX_INCLUDE_DIR AND QUICKERFIX_LIBRARIES)
